alias: null
attn_dropout: 0.4
batch_size: 64
check_val_every_n_epoch: 1
drop_last_loader: false
dropout: 0.4
early_stop_patience_steps: 10
exclude_insample_y: false
futr_exog_list: null
h: 100
hidden_size: 128
hist_exog_list:
- sma3
- sma2
- others_dlr
- others_dr
- log_return_2
- return2
- sma6
- sma12
- log_return_3
- return3
- log_return_6
- return6
- sma24
- hull_3
- hull_2
- sma48
- volume_fi
- log_return_12
- mid_diff
- return12
- momentum_roc
- sma96
- log_return_24
- hull_6
- return24
- sma144
- hull_12
- log_return_48
- return48
- momentum_wr
- momentum_stoch
- momentum_uo
- momentum_ppo
- hull_24
- momentum_ppo_hist
- volatility_dcp
- log_return_96
- volatility_kcli
- return96
- momentum_rsi
- hull_48
- volatility_kchi
- trend_macd_diff
- momentum_ppo_signal
- volatility_bbp
- sma_diff_12
- momentum_stoch_rsi
- sma288
- trend_kst
- volatility_ui
inference_windows_batch_size: 1024
input_size: 200
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.HuberLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  delta: 1.0
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
max_steps: 1000
n_head: 4
num_lr_decays: -1
num_workers_loader: 0
random_seed: 1
scaler_type: robust
start_padding_enabled: false
stat_exog_list: null
step_size: 1
tgt_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: !!python/object:neuralforecast.losses.pytorch.RMSE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
windows_batch_size: 1024
